#!/usr/bin/env bash
# Script: 0-transfer_file
# Description: This script transfers a file from the client to a server using SCP.
# Parameters:
#   1. PATH_TO_FILE: The path to the file to be transferred.
#   2. IP: The IP address of the server to transfer the file to.
#   3. USERNAME: The username that SCP connects with.
#   4. PATH_TO_SSH_KEY: The path to the SSH private key that SCP uses.

# Check if the required number of parameters is passed
if [ "$#" -lt 4 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
# Transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
