#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.
# Execute the script to install Nginx web server

# Update package lists
apt-get update

# Install nginx
apt-get install -y nginx

# Configure the redirection

cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location / {
        root /var/www/html;
        index index.html
     }

    location /redirect_me {
        return 301 https://www.youtube.com;
    }

    # Include other server configuration if needed
}
EOF

# Restart Nginx to apply the changes
service nginx restart
