#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.
# Execute the script to install Nginx web server
./1-install_nginx_web_server

# Configure the redirection

cat <<EOF > /etc/nginx/sites-available/redirect.conf
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    # Include other server configuration if needed
}
EOF

# Enable the new server block by creating a symbolic link
sudo ln -s /etc/nginx/sites-available/redirect.conf /etc/nginx/sites-enabled/

# Test Nginx configuration
sudo nginx -t

# Restart Nginx to apply the changes
sudo service nginx restart
