#!/usr/bin/env bash

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.9
apt-get install haproxy=2.9.\*
# Configure hostnames on lb-01 server
sudo hostnamectl set-hostname 100.25.0.91

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null << EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend my_frontend
    bind *:80
    default_backend my_backend

backend my_backend
    balance roundrobin
    server web-01 54.87.124.134:80 check
    server web-02 54.160.112.158:80 check 
EOF

# Restart HAProxy 
sudo systemctl restart haproxy

echo "HAProxy setup complete!"
