#!/usr/bin/env bash
# - a Bash script that pings an IP address passed as an argument.
# - Accepts a string as an argument
# - Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed
# - Ping the IP 5 times

# Check if an argument is provided
if [ $# -eq 0 ]; then
	echo "Usage: $0 {IP_ADDRESS}"
	exit 1
fi

# Get the IP address from the command-line argument
ip_address=$1

# Ping the address 5 times
ping -c 5 $ip_address

# Exit with the ping commands's exit status
exit $?
