#!/usr/bin/env bash
#A Bash (init) script 101-manage_my_process that manages manage_my_process

case "$1" in
	start)
		./manage_my_process &
		echo "$!" > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		pid=$(cat /var/run/my_process.pid)
		kill "$pid"
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		;;
	restart)
		pid=$(cat /var/run/my_process.pid)
		kill  "$pid"
		./manage_my_process &
		echo "$!" > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac
exit 0
