#!/usr/bin/env bash
#Bash script that displays Best School 10 times, but for the 9th iteration,
counter=0
while [ $counter -le 10 ]
do
	if [ $counter -eq 9 ]; then
		echo "hi"
	fi
	echo "Best School"
	((counter++))
done

