#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 20 and:
# - displays "bad luck from China" for the 4th loop iteration
# - displays "bad luck from Japan" for the 9th loop iteration
# - displays "bad luck from Italy" for the 17th loop iteration

counter=1

while [ $counter -le 20 ]
do
	echo "$counter"

	#Check if the current iteration matches any of the conditions.
	case $counter in 
		4) echo "bad luck from China" ;;
		9) echo "bad luck from Japan" ;;
		17) echo "bad luck from Italy" ;;
	esac
	(( counter++ ))
done
