#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes
# - display hours from 0 to 12
# - display minutes from 1 to 59

# Initialize hours and minutes
hours=0
minutes=1

while [ "$hours" -le 12 ]; do
	# Display hour
	echo "Hour: $hours"

	# Display minutes from 1 to 59
	seq 1 59

	# Increment minutes
	((hours++))

	# Check if minutes reached 60, reset minutes to 1 and increment
	# hours
	if [ "$hours" -eq 13 ]; then
		hours=1
	fi
done

