#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server.
# - localhost resolves to 127.0.0.2
# - facebook.com resolves to 8.8.8.8
# Set the IP address for localhost to 127.0.0.2

# Check if script is run as root
if [ "$EUID" -ne 0 ];then
	echo "Please run this script as root using sudo."
	exit 1
fi

# Backup the original hosts file 
cp /etc/hosts /etc/hosts.old

echo "127.0.0.2	localhost" >> /etc/hosts

# Set the IP address for facebook.com to 8.8.8.8
echo "8.8.8.8	facebook.com" >> /etc/hosts
